
create table animal (
  species                       varchar(255) not null,
  id                            bigint generated by default as identity not null,
  shelter_id                    bigint,
  version                       bigint not null,
  name                          varchar(255),
  registration_number           varchar(255),
  date_of_birth                 date,
  dog_size                      varchar(255),
  constraint pk_animal primary key (id)
);

create table animal_shelter (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  version                       bigint not null,
  constraint pk_animal_shelter primary key (id)
);

create table o_customer (
  id                            integer generated by default as identity not null,
  status                        varchar(1),
  name                          varchar(40) not null,
  smallnote                     varchar(100),
  anniversary                   date,
  billing_address_id            integer,
  shipping_address_id           integer,
  cretime                       timestamp not null,
  updtime                       timestamp not null,
  version                       bigint not null,
  constraint ck_o_customer_status check ( status in ('N','A','I')),
  constraint pk_o_customer primary key (id)
);

-- Creating the table for TestPackage1
create table test_package1 (
                               id BIGINT PRIMARY KEY AUTO_INCREMENT,  -- Primary key
                               current_time_stamp TIMESTAMP,            -- Formula field (included here for completeness)
                               version varchar(255)
);

-- Creating the table for TestPackage2
create table test_package2 (
                               id BIGINT PRIMARY KEY AUTO_INCREMENT,   -- Primary key
                               when_created TIMESTAMP,                 -- When the entity was created
                               test_package_id BIGINT,                -- Foreign key reference to TestPackage1
                               CONSTRAINT fk_test_package1
                                   FOREIGN KEY (test_package_id)
                                       REFERENCES test_package1(id) ON DELETE CASCADE -- Setting up the relationship with TestPackage1
);
