
name: Oracle

on:
  workflow_dispatch:
  schedule:
    - cron: '10 6 * * 1,4'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        java_version: [11]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'zulu'
    - name: Maven cache
      uses: actions/cache@v3
      env:
        cache-name: maven-cache
      with:
        path:
          ~/.m2
        key: build-${{ env.cache-name }}
    - name: maven-settings
      uses: s4u/maven-settings-action@v2
      with:
        servers: '[{"id": "github-release", "username": "dummy", "password": "${GITHUB_TOKEN}"}]'
        githubServer: false
    - name: oracle
      run: mvn -T 8 clean test -Dprops.file=testconfig/ebean-oracle.properties -Pgithub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
